[package]
name = "rslock"
version = "0.1.0"
authors = ["Isaac Freund <ifreund@ifreund.xyz>"]
edition = "2018"

[dependencies]
smithay-client-toolkit = { git = "https://github.com/Smithay/client-toolkit" }
