[package]
name = "rslock"
version = "0.1.0"
authors = ["Isaac Freund <isaac.a.freund@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
tempfile = "3.1.0"
wayland-client = "0.24.0"
wayland-protocols = { version = "0.24.0", features = ["client", "unstable_protocols"] }
xkbcommon = { version = "0.4.0", features = ["wayland"] }
