[package]
name = "rslock"
version = "0.1.0"
authors = ["Isaac Freund <ifreund@ifreund.xyz>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
pam = "0.7.0"
smithay-client-toolkit = "0.7.0"
users = "0.8.1"
