[package]
name = "waylock"
version = "0.1.0"
authors = ["Isaac Freund <ifreund@ifreund.xyz>"]
edition = "2018"

[dependencies]
cairo-rs = "0.8"
clap = "2"
pam = "0.7"
smithay-client-toolkit = "0.8"
users = "0.9"
